name: "CI"

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  lintAndTest:
    name: Lint & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1
      - name: Use Node.js v12
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Install Packages
        run: yarn install
      - name: Format Check
        run: yarn format-check
      - name: Lint
        run: yarn lint
      - name: Test
        run: yarn test
      - name: Run Action Code
        uses: ./

  scan:
    name: Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1
      - name: OSS Scan
        uses: shoprunner/action-oss@main